export async function GET(request: Request) {
//   const url = new URL(request.url);
//   const ids = url.searchParams.get("ids") || "1,2,3";
//   const API_KEY = process.env.CRYPTO_API_KEY;
//   const response = await fetch(
//     `https://pro-api.coinmarketcap.com/v2/cryptocurrency/info?id=${ids}`,
//     {
//       headers: {
//         "X-CMC_PRO_API_KEY": API_KEY!,
//       },
//     }
//   );

//   const res = await response.json();
  return Response.json(data);
}

const data = {
  "1": {
    id: 1,
    name: "Bitcoin",
    symbol: "BTC",
    category: "coin",
    description:
      "Bitcoin (BTC) is a cryptocurrency launched in 2010. Users are able to generate BTC through the process of mining. Bitcoin has a current supply of 19,815,159. The last known price of Bitcoin is 105,081.45329934 USD and is up 0.07 over the last 24 hours. It is currently trading on 11878 active market(s) with $21,988,386,676.31 traded over the last 24 hours. More information can be found at https://bitcoin.org/.",
    slug: "bitcoin",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png",
    subreddit: "bitcoin",
    notice: "",
    tags: [
      "mineable",
      "pow",
      "sha-256",
      "store-of-value",
      "state-channel",
      "coinbase-ventures-portfolio",
      "three-arrows-capital-portfolio",
      "polychain-capital-portfolio",
      "binance-labs-portfolio",
      "blockchain-capital-portfolio",
      "boostvc-portfolio",
      "cms-holdings-portfolio",
      "dcg-portfolio",
      "dragonfly-capital-portfolio",
      "electric-capital-portfolio",
      "fabric-ventures-portfolio",
      "framework-ventures-portfolio",
      "galaxy-digital-portfolio",
      "huobi-capital-portfolio",
      "alameda-research-portfolio",
      "a16z-portfolio",
      "1confirmation-portfolio",
      "winklevoss-capital-portfolio",
      "usv-portfolio",
      "placeholder-ventures-portfolio",
      "pantera-capital-portfolio",
      "multicoin-capital-portfolio",
      "paradigm-portfolio",
      "bitcoin-ecosystem",
      "ftx-bankruptcy-estate",
      "2017-2018-alt-season",
    ],
    "tag-names": [
      "Mineable",
      "PoW",
      "SHA-256",
      "Store Of Value",
      "State Channel",
      "Coinbase Ventures Portfolio",
      "Three Arrows Capital Portfolio",
      "Polychain Capital Portfolio",
      "Binance Labs Portfolio",
      "Blockchain Capital Portfolio",
      "BoostVC Portfolio",
      "CMS Holdings Portfolio",
      "DCG Portfolio",
      "DragonFly Capital Portfolio",
      "Electric Capital Portfolio",
      "Fabric Ventures Portfolio",
      "Framework Ventures Portfolio",
      "Galaxy Digital Portfolio",
      "Huobi Capital Portfolio",
      "Alameda Research Portfolio",
      "a16z Portfolio",
      "1Confirmation Portfolio",
      "Winklevoss Capital Portfolio",
      "USV Portfolio",
      "Placeholder Ventures Portfolio",
      "Pantera Capital Portfolio",
      "Multicoin Capital Portfolio",
      "Paradigm Portfolio",
      "Bitcoin Ecosystem",
      "FTX Bankruptcy Estate ",
      "2017/18 Alt season",
    ],
    "tag-groups": [
      "OTHERS",
      "ALGORITHM",
      "ALGORITHM",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "CATEGORY",
      "PLATFORM",
      "CATEGORY",
      "CATEGORY",
    ],
    urls: {
      website: ["https://bitcoin.org/"],
      twitter: [],
      message_board: ["https://bitcointalk.org"],
      chat: [],
      facebook: [],
      explorer: [
        "https://blockchain.info/",
        "https://live.blockcypher.com/btc/",
        "https://blockchair.com/bitcoin",
        "https://explorer.viabtc.com/btc",
        "https://www.okx.com/web3/explorer/btc",
      ],
      reddit: ["https://reddit.com/r/bitcoin"],
      technical_doc: ["https://bitcoin.org/bitcoin.pdf"],
      source_code: ["https://github.com/bitcoin/bitcoin"],
      announcement: [],
    },
    platform: null,
    date_added: "2010-07-13T00:00:00.000Z",
    twitter_username: "",
    is_hidden: 0,
    date_launched: "2010-07-13T00:00:00.000Z",
    contract_address: [],
    self_reported_circulating_supply: null,
    self_reported_tags: null,
    self_reported_market_cap: null,
    infinite_supply: false,
  },
  "2": {
    id: 2,
    name: "Litecoin",
    symbol: "LTC",
    category: "coin",
    description:
      "Litecoin (LTC) is a cryptocurrency . Users are able to generate LTC through the process of mining. Litecoin has a current supply of 84,000,000 with 75,461,112.0540992 in circulation. The last known price of Litecoin is 123.77508852 USD and is down -0.69 over the last 24 hours. It is currently trading on 1310 active market(s) with $1,062,158,822.88 traded over the last 24 hours. More information can be found at https://litecoin.org/.",
    slug: "litecoin",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/2.png",
    subreddit: "litecoin",
    notice: "",
    tags: [
      "mineable",
      "pow",
      "scrypt",
      "medium-of-exchange",
      "heco-ecosystem",
      "2017-2018-alt-season",
      "hoo-smart-chain-ecosystem",
      "made-in-america",
    ],
    "tag-names": [
      "Mineable",
      "PoW",
      "Scrypt",
      "Medium of Exchange",
      "HECO Ecosystem",
      "2017/18 Alt season",
      "Hoo Smart Chain Ecosystem",
      "Made in America",
    ],
    "tag-groups": [
      "OTHERS",
      "ALGORITHM",
      "ALGORITHM",
      "INDUSTRY",
      "PLATFORM",
      "CATEGORY",
      "PLATFORM",
      "CATEGORY",
    ],
    urls: {
      website: ["https://litecoin.org/"],
      twitter: ["https://twitter.com/litecoin"],
      message_board: [
        "https://litecointalk.io/",
        "https://litecoin-foundation.org/",
      ],
      chat: ["https://telegram.me/litecoin"],
      facebook: [],
      explorer: [
        "https://blockchair.com/litecoin",
        "https://chainz.cryptoid.info/ltc/",
        "http://explorer.litecoin.net/chain/Litecoin",
        "https://www.okx.com/web3/explorer/ltc",
        "https://bscscan.com/token/0x4338665cbb7b2485a8855a139b75d5e34ab0db94",
      ],
      reddit: ["https://reddit.com/r/litecoin"],
      technical_doc: [],
      source_code: ["https://github.com/litecoin-project/litecoin"],
      announcement: ["https://bitcointalk.org/index.php?topic=47417.0"],
    },
    platform: {
      id: "1839",
      name: "BNB",
      slug: "bnb",
      symbol: "BNB",
      token_address: "0x4338665cbb7b2485a8855a139b75d5e34ab0db94",
    },
    date_added: "2013-04-28T00:00:00.000Z",
    twitter_username: "litecoin",
    is_hidden: 0,
    date_launched: null,
    contract_address: [
      {
        contract_address: "0x4338665cbb7b2485a8855a139b75d5e34ab0db94",
        platform: {
          name: "BNB Smart Chain (BEP20)",
          coin: {
            id: "1839",
            name: "BNB",
            symbol: "BNB",
            slug: "bnb",
          },
        },
      },
      {
        contract_address: "0xecb56cf772b5c9a6907fb7d32387da2fcbfb63b4",
        platform: {
          name: "HECO",
          coin: {
            id: "2502",
            name: "Huobi Token",
            symbol: "HT",
            slug: "htx-token",
          },
        },
      },
      {
        contract_address: "0x13e93721dc992b3e14333dbdb48c0e7ec55431c3",
        platform: {
          name: "Hoo Smart Chain",
          coin: {
            id: "15165",
            name: "Hoo Smart Chain",
            symbol: "HSC",
            slug: "hoo-smart-chain",
          },
        },
      },
    ],
    self_reported_circulating_supply: null,
    self_reported_tags: null,
    self_reported_market_cap: null,
    infinite_supply: false,
  },
  "3": {
    id: 3,
    name: "Namecoin",
    symbol: "NMC",
    category: "coin",
    description:
      "Namecoin (NMC) is a cryptocurrency . Users are able to generate NMC through the process of mining. Namecoin has a current supply of 14,736,400. The last known price of Namecoin is 1.05572286 USD and is down -0.69 over the last 24 hours. It is currently trading on 7 active market(s) with $8,098.42 traded over the last 24 hours. More information can be found at https://www.namecoin.org/.",
    slug: "namecoin",
    logo: "https://s2.coinmarketcap.com/static/img/coins/64x64/3.png",
    subreddit: "namecoin",
    notice: "",
    tags: ["mineable", "pow", "sha-256", "platform"],
    "tag-names": ["Mineable", "PoW", "SHA-256", "Platform"],
    "tag-groups": ["OTHERS", "ALGORITHM", "ALGORITHM", "CATEGORY"],
    urls: {
      website: ["https://www.namecoin.org/"],
      twitter: ["https://twitter.com/Namecoin"],
      message_board: [],
      chat: ["https://www.namecoin.org/resources/chat/"],
      facebook: [],
      explorer: [
        "https://nmc.tokenview.com/",
        "https://www.namebrow.se/",
        "https://namecha.in/",
        "https://chainz.cryptoid.info/nmc/",
      ],
      reddit: ["https://reddit.com/r/namecoin"],
      technical_doc: ["https://www.namecoin.org/resources/whitepaper/"],
      source_code: ["https://github.com/namecoin"],
      announcement: ["https://bitcointalk.org/?topic=6017.0"],
    },
    platform: null,
    date_added: "2013-04-28T00:00:00.000Z",
    twitter_username: "Namecoin",
    is_hidden: 0,
    date_launched: null,
    contract_address: [],
    self_reported_circulating_supply: null,
    self_reported_tags: null,
    self_reported_market_cap: null,
    infinite_supply: false,
  },
};